import "/styles/globals.scss";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "next-cli",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(process);
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
